INSERT INTO `mlite_users` VALUES ("1", "admin", "Administrator", "Admin ganteng baik hati, suka menabung dan tidak sombong.", "$2y$10$yRQmDWOXM0PhoKZ.1.kix.K.Ckw8oR1i/ToPAR/WYRt/4SDD5u1eO",NULL,NULL,NULL, "avatar676e3e79ec70b.png", "adminfe@gmail.com", "admin", "all");
INSERT INTO `mlite_users` VALUES ("2", "DR000002", "dr. Fenty Sulistyo E", "Akun kusus dokter", "$2y$10$L95k.twSe275NULURrNwjOase6kZkZ1Nq8UWboYFw4F.4VS5Al.Am",NULL,NULL,NULL, "avatar676e40f62bcf0.png", "drfenty@gmail.com", "admin", "pasien,pendaftaran,kasir,master,laporan,blog,pcare,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("3", "pendaftaran", "pendaftaran", "-", "$2y$10$XkzxPAai/Yv6lUsal1eSB.S6DybcFKyhUi0NfcjbkiK1nn3LwvYL2",NULL,NULL,NULL, "avatar688ac4993f72e.png", "pendaftaran@gmail.com", "pengguna", "pasien,master,laporan,blog,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("4", "apotek", "apotek", "-", "$2y$10$w0y.GL116spz2tn4dlHmfeokZDChDtxmBUjF4G7jwMGfBPCvrdlnm",NULL,NULL,NULL, "avatar688ac4d09aa8f.png", "apotek@gmail.com", "apoteker", "kasir,master,laporan,blog,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("5", "perawat", "perawat", "-", "$2y$10$bwori.fxI8YSbOeV6D6PLesRovzav40U1lbOFM5DqvZsvoS3Xiy0i",NULL,NULL,NULL, "avatar688ac50b6dd0c.png", "perawat@gmail.com", "rekammedis", "pasien,pendaftaran,master,pcare,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("6", "aan", "siti wakhidatul a", "-", "$2y$10$pRHRDZ5HC52vBSR3EgVVZuasDZHbhBtUyGty2m/w1Ewn7q/bm8jJO",NULL,NULL,NULL, "avatar688d84942016a.png", "siti@gmail.com", "apoteker", "kasir,master,laporan,blog,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("7", "lutfia", "lutfia dyah damayanti", "-", "$2y$10$JrBo6VyB2xTvgsQHWf3Zyut40ZKkG1rrSfv/4eGaX7As7mOagtjwO",NULL,NULL,NULL, "avatar688d86306f6a2.png", "lutfia@gmail.com", "rekammedis", "pasien,pendaftaran,kasir,master,laporan,pcare,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("8", "anggi", "DESTIANA ANGGI P", "-", "$2y$10$4tLaorEMH/XkW7IJ/kEbE.5qxMy/8lU9elsGTauQYBYTaSfEx3zJi",NULL,NULL,NULL, "avatar688d86e6b6bf8.png", "anggi@gmail.com", "rekammedis","", "pasien,pendaftaran,master,laporan,pcare,satu_sehat,dashboard");
INSERT INTO `mlite_users` VALUES ("9", "subaktiar", "subaktiar", "-", "$2y$10$Mq1B3ZeW55lXRJkLJQ.mxeoyU2HLELxm5889v422I8Z42rfJo3qqq",NULL,NULL,NULL, "avatar688d8865aa1df.png", "tiar@gmail.com", "pengguna", "pasien,master,laporan,blog,pcare,satu_sehat,dashboard");

INSERT INTO `mlite_users` VALUES ("1","admin","Administrator","Admin ganteng baik hati, suka menabung dan tidak sombong.","$2y$10$pgRnDiukCbiYVqsamMM3ROWViSRqbyCCL33N8.ykBKZx0dlplXe9i",NULL,NULL,NULL,"avatar6422cb573b50c.png","info@mlite.id","admin","","all"),
("2","DR001","dr. Ataaka Muhammad","-","$2y$10$kuf2BxvViduBpUTn.6Nxsug3AskH/PGvXTSlfCfJqK8Ayb9a0.vqC",NULL,NULL,NULL,"avatar643a104444515.png","info@mlite.id","admin","","all");
